<?php
//@todo: unsubscribe confirmation, show event title
//@todo: theme the view
//@todo: build admin view
//@todo: export the view and add it to the module
//@todo: check why numbers are saved with +1 country code
//@todo: when subscibed as admin number is not enabled?
/**
 * @file
 * Find It specific implementation of Subscriber Entity.
 */

/**
 * Implements hook_menu().
 */
function findit_subscriber_menu() {
  // Lookup and redirect to subscriber/* entities.
  $items['subscriber'] = array(
    'title' => 'Update or create a subscription',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('findit_subscriber_lookup_form'),
    'access callback' => TRUE,
  );
  // Subscription to nodes on FindIt.
  $items['subscription/%node'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('findit_subscriber_addedit_form', 1),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  $items['subscription/confirm/%/%'] = array(
    'title' => 'Confirmation',
    'page callback' => 'findit_subscriber_confirm_page',
    'page arguments' => array(2),
    'access callback' => 'findit_subscriber_confirm_page_access',
    'access arguments' => array(2, 3),
  );

  $items['admin/config/system/findit-subscriber-email-templates'] = array(
    'title' => 'FindIt Subscriber Email & SMS Templates',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('findit_subscriber_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Settings form callback
 */
function findit_subscriber_admin_settings($form, &$form_state) {

  /*******EMAIL TEMPLATE********/
  $form['confirmation_mail'] = array(
    '#type' => 'fieldset',
    '#title' => t('Subscribe confirmation email'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );

  //Subject
  $form['confirmation_mail']['findit_subscriber_confirmation_mail_subject'] = array(
    '#type' => 'textfield',
    '#title' => t('Subject'),
    '#description' => t('The subject line of the email template. May include tokens of any token type specified below.'),
    '#default_value' => variable_get('findit_subscriber_confirmation_mail_subject', ''),
    '#required' => TRUE,
  );

  //Body
  $form['confirmation_mail']['findit_subscriber_confirmation_mail_body'] = array(
    '#title' => t('Body'),
    '#type' => 'textarea',
    '#description' => t('The body of the email template. May include tokens of any token type specified below.'),
    '#default_value' => variable_get('findit_subscriber_confirmation_mail_body', ''),
  );


  /*******EMAIL TEMPLATE********/
  $form['event_notify_email'] = array(
    '#type' => 'fieldset',
    '#title' => t('Event notification email'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );

  //Subject
  $form['event_notify_email']['findit_subscriber_event_notify_mail_subject'] = array(
    '#type' => 'textfield',
    '#title' => t('Subject'),
    '#description' => t('The subject line of the email template. May include tokens of any token type specified below.'),
    '#default_value' => variable_get('findit_subscriber_event_notify_mail_subject', ''),
    '#required' => TRUE,
  );

  //Body
  $form['event_notify_email']['findit_subscriber_event_notify_mail_body'] = array(
    '#title' => t('Body'),
    '#type' => 'textarea',
    '#description' => t('The body of the email template. May include tokens of any token type specified below.'),
    '#default_value' => variable_get('findit_subscriber_event_notify_mail_body', ''),
  );


  /*******EMAIL TEMPLATE********/
  $form['event_post_notify_email'] = array(
    '#type' => 'fieldset',
    '#title' => t('Event post-notification email'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );

  //Subject
  $form['event_post_notify_email']['findit_subscriber_post_notify_mail_subject'] = array(
    '#type' => 'textfield',
    '#title' => t('Subject'),
    '#description' => t('The subject line of the email template. May include tokens of any token type specified below.'),
    '#default_value' => variable_get('findit_subscriber_post_notify_mail_subject', ''),
    '#required' => TRUE,
  );

  //Body
  $form['event_post_notify_email']['findit_subscriber_post_notify_mail_body'] = array(
    '#title' => t('Body'),
    '#type' => 'textarea',
    '#description' => t('The body of the email template. May include tokens of any token type specified below.'),
    '#default_value' => variable_get('findit_subscriber_post_notify_mail_body', ''),
  );

  /*******SMS TEMPLATES********/
  $form['sms_templates'] = array(
    '#type' => 'fieldset',
    '#title' => t('SMS templates'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );

  $form['sms_templates']['findit_subscriber_confirmation_sms'] = array(
    '#type' => 'textarea',
    '#title' => t('Confirmation text'),
    '#description' => t('The text of the confirmation SMS. May include tokens of any token type specified below.'),
    '#default_value' => variable_get('findit_subscriber_confirmation_sms', ''),
    '#required' => TRUE,
  );

  $form['sms_templates']['findit_subscriber_event_notify_sms'] = array(
    '#type' => 'textarea',
    '#title' => t('Event notification text'),
    '#description' => t('The text of the event notification SMS. May include tokens of any token type specified below.'),
    '#default_value' => variable_get('findit_subscriber_event_notify_sms', ''),
    '#required' => TRUE,
  );

  $form['sms_templates']['findit_subscriber_post_notify_sms'] = array(
    '#type' => 'textarea',
    '#title' => t('Event post-notification text'),
    '#description' => t('The text of the event post-notification SMS. May include tokens of any token type specified below.'),
    '#default_value' => variable_get('findit_subscriber_post_notify_sms', ''),
    '#required' => TRUE,
  );

  //Token browser
  $form['tokens'] = array(
    '#theme' => 'token_tree',
    '#token_types' => array('node', 'event_subscriber'),
  );

  return system_settings_form($form);
}
/**
 * Implements hook_voipscript_get_script_names().
 */
function findit_subscriber_voipscript_get_script_names() {
  return array(
    'findit_subscriber_receive_confirmation',
  );
}

/**
 * Implements hook_voipscript_load_script().
 */
function findit_subscriber_voipscript_load_script($script_name, $params = NULL) {
  if (!in_array($script_name, findit_subscriber_voipscript_get_script_names())) {
    return;
  }
  require_once dirname(__FILE__) . '/findit_subscriber.voipscripts.inc';
  return $script_name();
}

/**
 * Implements hook_mail().
 */
function findit_subscriber_mail($key, &$message, $params) {
  switch ($key) {
    case 'confirmation':
      return findit_subscriber_confirmation_mail($message, $params['subscriber']);

    case 'event_notification':
      return findit_subscriber_event_notify_mail($message, $params['node']);

    case 'event_post_notification':
      return findit_subscriber_post_notify_mail($message, $params['node'], $params['action']);
  }
}

/****
 * Subscription: To a node
 *
 * Custom block and submit handler to allow for using same form to directly
 * subscribe to a node notifications using either mobile number or email.
 */

/**
 * Implements hook_block_info().
 */
function findit_subscriber_block_info() {
  $blocks['link'] = array(
    'info' => t('Subscription link'),
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function findit_subscriber_block_view($delta) {
  switch ($delta) {
    case 'link':
      return findit_subscriber_link_block();
  }
}

/**
 * Displays
 *
 * @return type
 */
function findit_subscriber_link_block() {
  $block = array();

  if (menu_get_item()['path'] != 'node/%') {
    return;
  }

  $node = menu_get_object();
  if(findit_subscriber_is_active_event($node)) {
    //Show Sign up link only for active events
    $block['content'] = array(
      '#theme' => 'link',
      '#text' => t('Sign up for @type reminder', array('@type' => $node->type)),
      '#path' => "subscription/$node->nid",
      '#options' => array(
        'attributes' => array(),
        'html' => FALSE,
        'query' => drupal_get_destination(), //add ?destination param
      ),
    );
  }

  return $block;
}

/**
 * Form constructor for subscription form.
 */
function findit_subscriber_addedit_form($form, &$form_state, $node) {
  drupal_set_title(t('__Reminder\'s Subscription__'));

  /*if ($node->type == 'event') {
    $title = t('Event reminder');
    $description = t('Enter your e-mail or mobile number to receive a reminder the day before this event.');
  }*/
  $form['nid'] = array(
    '#type' => 'value',
    '#value' => $node->nid,
  );
  $form['type'] = array(
    '#type' => 'value',
    '#value' => $node->type,
  );
 /* $form['subscriber_id'] = array(
    '#title' => $title,
    '#type' => 'textfield',
    '#size' => 15,
    '#description' => $description,
    '#required' => TRUE,
  );*/

  $form['subscriber_type'] = array(
    '#type' => 'radios',
    '#required' => TRUE,
    '#title' => t('How you would like to receive reminders for "@name"?', array('@name' => $node->title)),
    '#options' => (array('email'=>t('Email'), 'sms' => t('SMS'))),
    );

  $form['subscriber_email'] = array(
    '#title' => 'Email',
    '#type' => 'textfield',
    '#size' => 15,
    '#description' => t('Enter your e-mail to receive a reminder the day before this event.'),
    //'#required' => TRUE,
    '#element_validate' => array('findit_subscriber_email_validate'),
    '#states' => array(
      'visible' => array(
        ':input[name="subscriber_type"]' =>  array(
          'value' => 'email',
        ),
      ),
    ),
  );

  $form['subscriber_phone'] = array(
    '#title' => 'Phone number',
    '#type' => 'textfield',
    '#size' => 10,
    '#description' => t('Enter your 10-digit phone number here to receive a reminder the day before this event.'),
    //'#required' => TRUE,
    '#element_validate' => array('findit_subscriber_sms_validate'),
    '#states' => array(
      'visible' => array(
        ':input[name="subscriber_type"]' =>  array(
          'value' => 'sms',
        ),
      ),
    ),
  );


  $form['submit'] = array('#type' => 'submit', '#value' => t('Save'));
  return $form;
}

function findit_subscriber_email_validate($element, &$form_state, $form) {
  $type = $form_state['values']['subscriber_type'];
  $value = $element['#value'];
  if ($type=='email' && $value && !valid_email_address($value)) {
    form_error($element, t('"%mail" is not a valid email address', array('%mail' => $value)));
  }
}

function findit_subscriber_sms_validate($element, &$form_state, $form) {
  $type = $form_state['values']['subscriber_type'];
  $value = $element['#value'];
  $error = findit_subscriber_validate_sms($value);
  if($type=='sms' && $value && $error) {
    form_error($element, $error);
  }
}

/**
 * Form validation handler for subscription form.
 *
 * @see findit_subscriber_addedit_form()
 */
/*
function findit_subscriber_addedit_form_validate($form, &$form_state) {
  $subscriber_id = $form_state['values']['subscriber_id'];
  $type = findit_subscriber_detect_type($subscriber_id);
  if ($type == 'sms') {
    if($error = findit_subscriber_validate_sms($subscriber_id)) {
      form_set_error($field['field_name'] . '][' . $langcode . '][' . $delta . '][vnid', $error);
    }
    else {
      $form_state['values']['subscriber_id'] = $subscriber_id;
    }
  }
  else {
    if ($error = findit_subscriber_validate_email($subscriber_id)) {
      form_set_error('subscriber_id', $error);
    }
    else {
      $form_state['values']['subscriber_id'] = $subscriber_id;
    }
  }
}
*/
/**
 * Form submission handler for subscription form.
 *
 * @see findit_subscriber_addedit_form()
 */
function findit_subscriber_addedit_form_submit($form, &$form_state) {
  //$subscriber_id = $form_state['values']['subscriber_id'];
  //$type = findit_subscriber_detect_type($subscriber_id);
  $type = $form_state['values']['subscriber_type'];

  if($type == 'email') {
    $subscriber_id = $form_state['values']['subscriber_email'];
  }
  else {
    $subscriber_id = $form_state['values']['subscriber_phone'];
  }
  // Left as variable in case organization subscriptions return.
  $field = FINDIT_FIELD_SUBSCRIBER_EVENTS;

  /*if (empty($form_state['values']['subscriber_id'])) {
    drupal_set_message(t('An email address or mobile number is required.'));
    return;
  }*/
  if ($subscriber = entity_load('subscriber_entity', array($subscriber_id))) {
    $subscriber = reset($subscriber);
    $new = FALSE;
  }
  else {
    $subscriber = findit_subscriber_create($type, $subscriber_id);
    $new = TRUE;
  }

  // Add or remove.
  $addition = TRUE;
  if (!empty($subscriber->$field)) {
    foreach ($subscriber->{$field}[LANGUAGE_NONE] as $delta => $existing_values) {
      if ($existing_values['target_id'] == $form_state['values']['nid']) {
        $addition = FALSE;
        //unset($subscriber->{$field}[LANGUAGE_NONE][$delta]);
      }
    }
  }
  if ($addition) {
    $subscriber->{$field}[LANGUAGE_NONE][] = array('target_id' => $form_state['values']['nid']);
  }

  if (subscriber_entity_access('revision')) {
    if ($addition) {
      $node = node_load($form_state['values']['nid']);
      drupal_set_message(t('You are now subscribed to %node_title reminders.', array('%node_title' => $node->title)));
    }
    else {
      //drupal_set_message(t('Subscription removed.'));
      drupal_set_message('You are already subscribed.');
    }
  }
  else {
    if ($addition) {
      if ($new) {
        // If this is a new subscription first save a disabled subscription.
        // Then make an enabled revision that can be confirmed.
        $subscriber->{FINDIT_FIELD_SUBSCRIBER_ENABLED}[LANGUAGE_NONE][0]['value'] = 0;
        $subscriber->save();
        $subscriber->{FINDIT_FIELD_SUBSCRIBER_ENABLED}[LANGUAGE_NONE][0]['value'] = 1;
      }
      $subscriber->is_new_revision = TRUE;
      $subscriber->default_revision = FALSE;
      if ($new) {
        drupal_set_message(t('New subscription added. Please reply to message sent to confirm.'));
      }
      else {
        drupal_set_message(t('Existing subscription updated. Please reply to message sent to confirm.'));
      }
    }
    else {
      //drupal_set_message(t('Subscription removed.'));
      drupal_set_message('You are already subscribed');
    }
  }

  $subscriber->changed = time();
  $subscriber->save();

  if (!subscriber_entity_access('revisions') && $addition) {
    $message = findit_subscriber_request_confirmation($subscriber);
    drupal_set_message($message);
  }
}

/****
 * Subscriber: Look-up, create and edit.
 *
 * A form to redirect to the subscriber entity edit form. Form alters
 * from the default entity edit for FindIt sms/email.
 */

/**
 * Form constructor to lookup an individual subscriber.
 */
function findit_subscriber_lookup_form($form, &$form_state) {
  $form['subscriber_id'] = array(
    '#title' => t('Mobile number or e-mail address'),
    '#type' => 'textfield',
    '#size' => 15,
    '#description' => t('Enter the e-mail or mobile number for subscriptions'),
    '#required' => TRUE,
  );
  $form['submit'] = array('#type' => 'submit', '#value' => t('Submit'));
  return $form;
}

/**
 * Form validate callback.
 *
 * @see subscriber_entity_lookup_form()
 */
function findit_subscriber_lookup_form_validate($form, &$form_state) {
  $subscriber_id = $form_state['values']['subscriber_id'];
  $type = findit_subscriber_detect_type($subscriber_id);
  if ($type == 'sms') {
    if($error = findit_subscriber_validate_sms($subscriber_id)) {
      form_set_error($field['field_name'] . '][' . $langcode . '][' . $delta . '][vnid', $error);
    }
    else {
      $form_state['values']['subscriber_id'] = $subscriber_id;
    }
  }
  else {
    if ($error = findit_subscriber_validate_email($subscriber_id)) {
      form_set_error('subscriber_id', $error);
    }
    else {
      $form_state['values']['subscriber_id'] = $subscriber_id;
    }
  }
}

/**
 * Form submit callback.
 *
 * @see subscriber_entity_lookup_form()
 */
function findit_subscriber_lookup_form_submit($form, &$form_state) {
  $subscriber_id = $form_state['values']['subscriber_id'];
  watchdog('debug',$subscriber_id);
  $type = findit_subscriber_detect_type($subscriber_id);

  if ($subscriber = entity_load('subscriber_entity', array($subscriber_id))) {
    $subscriber = reset($subscriber);
    drupal_set_message(t('Subscription loaded'));
    drupal_goto('subscriber/' . $subscriber->id . '/edit');
  }
  else {
    drupal_set_message(t('New subscriber'));
    drupal_set_message(t('%subscriber_id is a new subscription', array('%subscriber_id' => $form_state['values']['subscriber_id'])));
    drupal_goto('subscriber/add/' . $type, array('query' => array('subscriber_id' => $form_state['values']['subscriber_id'])));
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * @see subscriber_entity_edit_form()
 */
function findit_subscriber_form_subscriber_entity_edit_form_alter(&$form, &$form_state) {
  $type = $form['#bundle'];
  $bundle = entity_load('subscriber_entity_bundle', array($type));
  $bundle = reset($bundle);
  $field_name = $bundle->unique_field;

  // If this is a new subscription the default is disabled. Responding
  // to confirmation enables.
  if (empty($form['subscriber_id']['#value']) && !subscriber_entity_access('revision')) {
    unset($form['field_subscriber_enabled']);
  }
  // Add default if included in url.
  if (! empty($_GET['subscriber_id'])) {
    if ($type == 'sms') {
      $form[$field_name][LANGUAGE_NONE][0]['#default_value']['vnid'] = check_plain($_GET['subscriber_id']);
    }
    else {
      $form[$field_name][LANGUAGE_NONE][0]['email']['#default_value'] = check_plain($_GET['subscriber_id']);
    }
  }
  $form['#validate'][] = 'findit_subscriber_subscriber_entity_edit_form_validate';
  $form['#submit'][] = $form['actions']['submit']['#submit'][] = 'findit_subscriber_subscriber_entity_edit_form_submit';
  $entity = $form['#entity'];
}

/**
 * Form submission callback.
 *
 * @see findit_subscriber_form_subscriber_entity_edit_form_alter()
 */
function findit_subscriber_subscriber_entity_edit_form_validate(&$form, &$form_state) {
  if (empty($form['subscriber_id']['#value']) && !subscriber_entity_access('revision')) {
    $form_state['values']['field_subscriber_enabled'][LANGUAGE_NONE][0]['value'] = 0;
  }
}


/**
 * Form submission callback.
 *
 * @see findit_subscriber_form_subscriber_entity_edit_form_alter()
 */
function findit_subscriber_subscriber_entity_edit_form_submit($form, &$form_state) {
  if (subscriber_entity_access('revision')) {
    // The user has access to update the revision directly, no additional
    // confirmation required.
    return;
  }

  $subscriber = $form_state['subscriber_entity'];
  watchdog('debug', print_r($subscriber,true));
  // Create an enabled revision if this is the first disabled save.
  if (empty($form['subscriber_id']['#value'])) {
    $subscriber->field_subscriber_enabled['und'][0]['value'] = 1;
    $subscriber->is_new_revision = TRUE;
    $subscriber->default_revision = FALSE;
    $subscriber->save();
  }
  $message = findit_subscriber_request_confirmation($subscriber);
  drupal_set_message($message);
}

/****
 * Helper functions
 */

/**
 * Detect type of subscriber from ID.
 *
 * @param string $subscriber_id
 *
 * @return string
 *   email | sms
 */
function findit_subscriber_detect_type($subscriber_id) {
  return strpos($subscriber_id, '@') ? 'email' : 'sms';
}

/**
 * Check if a SMS mobile number is valid.
 *
 * Also normalizes the subscriber_id parameter.
 * Watch that return it's backward.
 *
 * @param string &$subscriber_id
 *
 * @return bool|string
 *   FALSE if *valid*; error message if not.
 */
//@todo: improve, now numbers like a385, 48 will pass.
function findit_subscriber_validate_sms(&$subscriber_id) {
  // @see voipnumberfield_field_validate().
  $field_info = field_info_field(FINDIT_FIELD_SUBSCRIBER_VOIPNUMBER);
  $subscriber_id = voipnumberfield_format_number($subscriber_id, $field_info['settings']);
  $subscriber_id = VoipCall::NormalizeNumber($subscriber_id);
  $number_country_temp = VoipNumber::getCountryFromNumber($subscriber_id);
  $allowed = FALSE;
  if (!is_array($number_country_temp)) {
    //VoipNumber::getCountryFromNumber can return array of countries or string.
    $number_countries[] = $number_country_temp;
  }
  else {
    $number_countries = $number_country_temp;
  }
  $countries = $field_info['settings']['voipnumberfield_allowed_countries'];
  if (is_array($countries)) {
    // Since $number_countries can be multiple countries we need to check all.
    foreach ($number_countries as $number_country) {
      if (in_array($number_country, $countries)) {
        $allowed = TRUE;
      }
    }
  }

  if (!$allowed) {
    return t('Phone number is not recognized US number.');
  }
  else {
    return FALSE;
  }
}

/**
 * Check if a email address is valid.
 *
 * Watch that return it's backward.
 *
 * @param string &$subscriber_id
 *
 * @return bool|string
 *   FALSE if *valid*; error message if not.
 */
function findit_subscriber_validate_email(&$subscriber_id) {
  // @see email_field_validate().
  if (!valid_email_address(trim($subscriber_id))) {
    return t('"%mail" is not a valid email address', array('%mail' => $subscriber_id));
  }

  return FALSE;
}

/**
 * Create a new subscriber entity.
 *
 * @param string $type
 *   Bundle for the entity sms|email.
 * @param string $subscriber_id
 *   SMS number, or e-mail address.
 *
 * @return Subscriber
 *   Subscriber entity.
 */
function findit_subscriber_create($type, $subscriber_id) {
  $subscriber = entity_get_controller('subscriber_entity')->create(array('bundle' => $type));
  $subscriber->created = time();
  if ($type == 'sms') {
    $subscriber->{FINDIT_FIELD_SUBSCRIBER_VOIPNUMBER}[LANGUAGE_NONE][0]['vnid'] = $subscriber_id;
  }
  else {
    $subscriber->{FINDIT_FIELD_SUBSCRIBER_EMAIL}[LANGUAGE_NONE][0]['email'] = $subscriber_id;
  }

  return $subscriber;
}

/**
 * Send confirmation message.
 *
 * Written in this slightly abstract way as lead to generalize into subscriber entity
 * module.
 * Todo move into parent module.
 */
function findit_subscriber_request_confirmation($subscriber) {
  watchdog('debug', print_r($subscriber,true));
  $bundle = entity_load('subscriber_entity_bundle', array($subscriber->bundle));
  $bundle = reset($bundle);
  $field_name = $bundle->unique_field;

  $callback = 'findit_subscriber_request_confirmation_' . $subscriber->bundle;
  return $callback($subscriber, $field_name);
}

/**
 * Send SMS confirmation message.
 */
function findit_subscriber_request_confirmation_sms($subscriber, $field) {
  // Force a reload of subscriber entity, because at the moment the vnid is set
  // as the vnid rather than the 'real_vnid' and the number is missing.
  $subscriber_array = entity_load('subscriber_entity', array($subscriber->id), array(), TRUE);
  $subscriber = reset($subscriber_array);

  // Send confirmation SMS.
  $voipnumbers = field_get_items('subscriber_entity', $subscriber, $field);
  $number_render = field_view_value('subscriber_entity', $subscriber, $field, $voipnumbers[0]);
  $number = $number_render['#markup'];
  $call = new VoipCall();
  $call->setDestNumber($number);
  $text = variable_get('findit_subscriber_confirmation_sms', '');
  voip_text($text, $call);
  return t('A SMS has been sent to your phone for confirmation.');
}

/**
 * Send confirmation email.
 */
function findit_subscriber_request_confirmation_email($subscriber, $field) {
  drupal_mail(
    'findit_subscriber',
    'confirmation',
    $subscriber->{$field}[LANGUAGE_NONE][0]['email'],
    language_default(),
    array(
      //'url' => findit_subscriber_email_confirmation_url($subscriber),
      'subscriber' => $subscriber,
    )
  );
  return t('An email has been sent for confirmation.');
}


/**
 * Mail callback for confirmation message.
 *
 * @see findit_subscriber_mail()
 */
function findit_subscriber_confirmation_mail(&$message, $subscriber) {
  $language = $message['language'];
  $subject = variable_get('findit_subscriber_confirmation_mail_subject', '');
  $body = variable_get('findit_subscriber_confirmation_mail_body', '');

  $message['subject'] = token_replace($subject, array('subscriber' => $subscriber), array('language' => $language));
  $message['body'][] = token_replace($body, array('subscriber' => $subscriber), array('language' => $language));
}

/****
 * Confirmation handling.
 *
 * Confirmation can be called from incoming SMS, or from clicking
 * on a link in the email.
 *
 * @todo this could be moved on up as available api functions in
 * entity subscriber.
 */

/**
 * Menu access callback: subscription confirmation.
 */
function findit_subscriber_confirm_page_access($revision_id, $hash) {
  // Todo When moved into subscriber entity add a user check.
  // Find It we know anyone can access, as long as URL is correct.
  if (!($revision = entity_revision_load('subscriber_entity', $revision_id))) {
    return FALSE;
  }
  if ($hash != findit_subscriber_generate_hash($revision)) {
    return FALSE;
  }

  return TRUE;
}

/**
 * Menu callback; confirmation page for subscriptions.
 */
function findit_subscriber_confirm_page($revision_id) {
  $revision = entity_revision_load('subscriber_entity', $revision_id);
  if ($revision->default_revision) {
    return t('Subscription already confirmed.');
  }
  else {
    entity_revision_set_default('subscriber_entity', $revision);
    $revision->save();
    return t('Subscription %title has been confirmed.', array('%title' => $revision->subscriber_id));
  }
}

/**
 * Callback to update revision.
 */
function findit_subscriber_revision_update($caller_number) {
  // Extra space is casting workaround, we know it's a string.
  $subscription = subscriber_entity_load(' ' . $caller_number, 'sms');

  $entity_info = entity_get_info('subscriber_entity');
  $id = $entity_info['entity keys']['id'];
  $revision_key = $entity_info['entity keys']['revision'];
  $revision_table = $entity_info['revision table'];

  // Fetch latest updated revision.
  $revision = db_select($revision_table, 'r')
    ->fields('r')
    ->condition($id, $subscription->$id, '=')
    ->orderBy('changed', 'DESC')
    ->orderBy('revision_id', 'DESC')
    ->range(0, 1)
    ->execute()
    ->fetchAssoc();

  // If no revision _how_?
  if (!$revision) {
    return FALSE;
  }

  // If the present revision is the latest don't do anything.
  if ($revision[$revision_key] == $subscription->$revision_key) {
    return $subscription;
  }

  // Make the latest revision the default one.
  $new_subscription = entity_revision_load('subscriber_entity', $revision[$revision_key]);
  entity_revision_set_default('subscriber_entity', $new_subscription);
  $new_subscription->save();
  return $new_subscription;
}

function findit_subscriber_email_confirmation_url($entity_revision) {
  return url(
    'subscription/confirm/' . $entity_revision->revision_id . '/' . findit_subscriber_generate_hash($entity_revision),
    array('absolute' => TRUE)
  );
}

function findit_subscriber_generate_hash($entity, $action = 'confirm') {
  return drupal_hash_base64(
    $entity->subscriber_id
    . $entity->revision_id
    . findit_subscriber_private_key()
    . $action
    . $entity->changed
  );
}

function findit_subscriber_private_key() {
  if (!($key = variable_get('findit_subscriber_private_key', 0))) {
    $key = drupal_random_key();
    variable_set('findit_subscriber_private_key', $key);
  }
  return $key;
}


/****
 * Send notifications.
 *
 * Regular cron job to trigger sending SMS and email notifications for the site
 * specific messages (presently just events).
 */

/**
 * Implements hook_cron().
 */
function findit_subscriber_cron() {
  $last_run = variable_get('findit_subscriber_cron_run', '@0');
  $last_run_date = new DateTime($last_run);
  $yesterday = new DateTime('yesterday');
  $now = new DateTime();
  // Run notifications if they were last sent yesterday (or earlier),
  // and it is after 4 in the afternoon.
  if ($last_run_date <= $yesterday && $now->format('H') > 15) {
    findit_subscriber_notify_tomorrow();
    variable_set('findit_subscriber_cron_run', $now->format('Y-m-d'));
  }
}

/**
 * Implements hook_form_alter().
 *
 * Add option to choose if notification of creation/update is sent.
 */
function findit_subscriber_form_alter(&$form, &$form_state, $form_id) {
  //dpm($form_id);
  if($form_id == 'views_exposed_form') {
    //$form['#validate'][]='findit_subscriber_form_views_exposed_validate';
    array_unshift($form['#validate'], 'findit_subscriber_form_views_exposed_validate');

  }

  if (!in_array($form_id, array('event_node_form'))) {
    return;
  }

  $new = empty($form['nid']['#value']);
  if ($new && $form['#bundle'] == 'event') {
    // No one can have subscribed to an event before it is created.
    return;
  }

  if ($new) {
    $checkbox_title = t('Send notifications about this new announcement');
  }
  else {
    $checkbox_title = t('Send notifications about this update');
  }
  $form['findit_subscriber_notification'] = array(
    '#type' => 'fieldset',
    '#access' => TRUE,
    '#collapsed' => TRUE,
    '#group' => 'additional_settings',
    '#title' => t('Notifications'),
  );
  $form['findit_subscriber_notification']['findit_subscriber_notification_enabled'] = array(
    '#type' => 'checkbox',
    '#title' => $checkbox_title,
    '#default_value' => 1,
  );
}

/**
 * Implements hook_node_update().
 */
function findit_subscriber_node_update($node) {
  if (!empty($node->findit_subscriber_notification_enabled) && $node->status) {
    if ($node->type == 'event') {
      $subscribers = findit_subscriber_event_subscribers($node->nid);
      //SMS template:
      $text = variable_get('findit_subscriber_post_notify_sms', '');
      $text = token_replace($text, array('node' => $node), array('language' => language_default()));

      foreach ($subscribers as $subscriber) {
        if ($subscriber->bundle == 'sms') {
          findit_subscriber_queue_sms($subscriber, $text);
        }
        else {
          drupal_mail(
            'findit_subscriber',
            'event_post_notification',
            $subscriber->{FINDIT_FIELD_SUBSCRIBER_EMAIL}[LANGUAGE_NONE][0]['email'],
            language_default(),
            array(
              'node' => $node,
              'action' => 'update',
            )
          );
        }
      }
    }
  }
}

/**
 * Notify subscribers of tomorrows events.
 */
function findit_subscriber_notify_tomorrow() {
  $events = findit_subscriber_events_upcoming();

  foreach ($events as $event) {
    $subscribers = findit_subscriber_event_subscribers($event->nid);

    //SMS template
    $text = variable_get('findit_subscriber_event_notify_sms', '');
    $text = token_replace($text, array('node' => $event), array('language' => language_default()));

    foreach ($subscribers as $subscriber) {
     // $notifications[$subscriber->bundle][$subscriber->subscriber_id]['subscriber'] = $subscriber;
      //$notifications[$subscriber->bundle][$subscriber->subscriber_id]['events'][] = $event;

      if($subscriber->bundle == 'sms') {
        // Just send one text message per event to subscribers.
        findit_subscriber_queue_sms($subscriber, $text);
      }
      else if($subscriber->bundle == 'email') {
        //Send one email per event
        drupal_mail(
          'findit_subscriber',
          'event_notification',
          $subscriber->{FINDIT_FIELD_SUBSCRIBER_EMAIL}[LANGUAGE_NONE][0]['email'],
          language_default(),
          array(
            'node' => $event,
          )
        );
      }
    }
  }
/*
  if (!empty($notifications['sms'])) {
    // Just send one text message per event to subscribers.
    foreach ($notifications['sms'] as $notification) {
      $subscriber = $notification['subscriber'];
      foreach ($notification['events'] as $event) {
        findit_subscriber_queue_sms($subscriber, t('Reminder. Tomorrow @title', array('@title' => $event->title)));
      }
    }
  }

  if (!empty($notifications['email'])) {
    foreach ($notifications['email'] as $notification) {
      $subscriber = $notification['subscriber'];
      foreach ($notification['events'] as $event) {
        //Send one email per event
        drupal_mail(
          'findit_subscriber',
          'event_notification',
          $subscriber->{FINDIT_FIELD_SUBSCRIBER_EMAIL}[LANGUAGE_NONE][0]['email'],
          language_default(),
          array(
            'node' => $event,
          )
        );
      }
    }
  }*/
}

/**
 * Mail callback for event notification.
 *
 * @see findit_subscriber_mail()
 */
function findit_subscriber_event_notify_mail(&$message, $node) {
  //$langcode = $message['language']->language;
  $language = $message['language'];

  $subject = variable_get('findit_subscriber_event_notify_mail_subject', '');
  $body = variable_get('findit_subscriber_event_notify_mail_body', '');

  $message['subject'] = token_replace($subject, array('node' => $node), array('language' => $language));
  $message['body'][] = token_replace($body, array('node' => $node), array('language' => $language));


  /*$message['subject'] = t(
    'Find IT events tomorrow',
    array(),
    array('langcode' => $langcode)
  );*/
  /*$message['body'][] = format_plural(
    count($events),
    'An event you requested notification for happens tomorrow:',
    'Events you requested a notification for happen tomorrow:',
    array(),
    array('langcode' => $langcode)
  );
  foreach($events as $event) {
    $event_time_value = field_get_items('node', $event, FINDIT_FIELD_EVENT_DATE);
    $event_time_render = field_view_value(
      'node',
      $event,
      FINDIT_FIELD_EVENT_DATE,
      $event_time_value[0],
      array(
        'label' => 'hidden',
        // You can't set date_plain format settings ...
        // 'type' => 'date_plain',
        'settings' => array(
          'format_type' => 'medium',
          'show_remaining_days' => FALSE,
          'show_repeat_rule'    => 'show',
        ),
      ),
      $langcode
    );
    // ... However Date default puts in HTML. Bah!
    $event_time = strip_tags($event_time_render['#markup']);
    $message['body'][] = t(
      '@time : @title - !url',
      array(
        '@title' => $event->title,
        '@time' => $event_time,
        '!url' => url('node/' . $event->nid, array('absolute' => TRUE)),
      ),
      array('langcode' => $langcode)
    );
  }*/
}

/**
 * Mail callback for posting notification.
 *
 * @see findit_subscriber_mail()
 */
function findit_subscriber_post_notify_mail(&$message, $node, $action) {
  //$langcode = $message['language']->language;
  $language = $message['language'];


  $subject = variable_get('findit_subscriber_post_notify_mail_subject', '');
  $body = variable_get('findit_subscriber_post_notify_mail_body', '');

  $message['subject'] = token_replace($subject, array('node' => $node), array('language' => $language));
  $message['body'][] = token_replace($body, array('node' => $node), array('language' => $language));

  /*
  if ($node->type == 'event') {
    $message['subject'] = t(
      'Find IT event @title has been updated',
      array('@title' => $node->title),
      array('langcode' => $langcode)
    );
  }
  $message['body'][] = t(
    'Full @type at !url',
    array(
      '@type' => $node->type,
      '!url' => url('node/' . $node->nid, array('absolute' => TRUE)),
    ),
    array('langcode' => $langcode)
  );
  if ($node->type == 'event') {
    $event_time_value = field_get_items('node', $node, FINDIT_FIELD_EVENT_DATE);
    $event_time_render = field_view_value(
      'node',
      $node,
      FINDIT_FIELD_EVENT_DATE,
      $event_time_value[0],
      array(
        'label' => 'hidden',
        // You can't set date_plain format settings ...
        // 'type' => 'date_plain',
        'settings' => array(
          'format_type' => 'medium',
          'show_remaining_days' => FALSE,
          'show_repeat_rule'    => 'show',
        ),
      ),
      $langcode
    );
    // ... However Date default puts in HTML. Bah!
    $event_time = strip_tags($event_time_render['#markup']);
    $message['body'][] = t(
      'Event date: @time',
      array(
        '@time' => $event_time,
      ),
      array('langcode' => $langcode)
    );
  }
  $message['body'][] = check_plain($node->body[LANGUAGE_NONE][0]['value']);*/
  //@todo: run check_plain?
}


/**
 * Get array of all subscribers entities to an event node.
 */
function findit_subscriber_event_subscribers($nid) {
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'subscriber_entity');
  $query->fieldCondition(FINDIT_FIELD_SUBSCRIBER_EVENTS, 'target_id', $nid, '=');
  $query->fieldCondition(FINDIT_FIELD_SUBSCRIBER_ENABLED, 'value', 1, '=');
  $result = $query->execute();
  if (isset($result['subscriber_entity'])) {
    $ids = array_keys($result['subscriber_entity']);
  }
  else {
    $ids = array();
  }
  return entity_load('subscriber_entity', $ids);
}

/**
 * Get array of all tomorrows event nodes.
 *
 * Todo swap this to use its own view, or EFQ.
 */
function findit_subscriber_events_upcoming() {
  $tomorrow = new DateTime('tomorrow');
  $view = views_get_view('event_calendar');
  if (!$view) {
    // Should only happen before the site is fully initialized.
    watchdog('findit_subscriber', 'Missing view: Event calendar', array(), WATCHDOG_WARNING);
    return array();
  }
  $view->set_display('page_3');
  $view->set_arguments(array($tomorrow->format('Y-m-d')));
  $view->pre_execute();
  $view->execute();
  // Just because this is lazy using an existing field based view.
  $results = array();
  foreach ($view->result as $result) {
    $results[] = $result->_field_data['nid']['entity'];
  }
  return $results;
}

/**
 * Queue an SMS.
 */
function findit_subscriber_queue_sms($subscriber, $text, $queue = 'findit_notification') {
  $queue = DrupalQueue::get('findit_notification');
  $queue->createQueue();
  $call = new VoipCall(array());
  $number_items = field_get_items('subscriber_entity', $subscriber, FINDIT_FIELD_SUBSCRIBER_VOIPNUMBER);
  $number_render = field_view_value('subscriber_entity', $subscriber, FINDIT_FIELD_SUBSCRIBER_VOIPNUMBER, $number_items[0]);
  $call->setDestNumber($number_render['#markup']);
  $item = new VoipQueueText($call, $text);
  $item->tags = array('findit:' . $subscriber->id);
  $queue->createItem($item);
}

/**
 * Implements hook_token_info().
 *
 */
function findit_subscriber_token_info() {
  // Random tokens.
  $info['types']['event_subscriber'] = array(
    'name' => t('Event Subscriber'),
    'description' => ('Tokens related to event subscriber.'),
  );
  /*$info['tokens']['event_subscriber']['events_data'] = array(
    'name' => t('Events data'),
    'description' => t('List of events in format: @time : @title - !url'),
  );*/

  $info['tokens']['event_subscriber']['confirmation_url'] = array(
    'name' => t('Confirmation URL'),
    'description' => t('Event confirmation URL'),
  );

  $info['tokens']['node']['event_date'] = array(
    'name' => t('Event date'),
    'description' => t('Event date custom formatted.'),
  );

  return $info;
}

/**
 * Implements hook_tokens().
 */
function findit_subscriber_tokens($type, $tokens, array $data = array(), array $options = array()) {
  $replacements = array();
  if (isset($options['language'])) {
    $langcode = $options['language']->language;
  }
  else {
    $langcode = NULL;
  }
  if ($type == 'event_subscriber') {
    foreach ($tokens as $name => $original) {
      switch ($name) {
        case 'confirmation_url':
          if(!empty($data['subscriber'])) {
            $subscriber = $data['subscriber'];
            $replacements[$original] = findit_subscriber_email_confirmation_url($subscriber);
          }
          break;
        /*case 'events_data':
          if(!empty($data['events'])) {
            $events = $data['events'];
            foreach($events as $event) {
              $event_time_value = field_get_items('node', $event, FINDIT_FIELD_EVENT_DATE);
              $event_time_render = field_view_value(
                'node',
                $event,
                FINDIT_FIELD_EVENT_DATE,
                $event_time_value[0],
                array(
                  'label' => 'hidden',
                  // You can't set date_plain format settings ...
                  // 'type' => 'date_plain',
                  'settings' => array(
                    'format_type' => 'medium',
                    'show_remaining_days' => FALSE,
                    'show_repeat_rule'    => 'show',
                  ),
                ),
                $langcode
              );
              // ... However Date default puts in HTML. Bah!
              $event_time = strip_tags($event_time_render['#markup']);
              $replacements[$original] .= t(
                '@time : @title - !url',
                array(
                  '@title' => $event->title,
                  '@time' => $event_time,
                  '!url' => url('node/' . $event->nid, array('absolute' => TRUE)),
                ),
                array('langcode' => $langcode)
              );
            }
          }
          break;*/
      }
    }
  }
  else if ($type == 'node' && !empty($data['node'])) {
    $node = $data['node'];
    foreach ($tokens as $name => $original) {
      switch ($name) {
        case 'event_date':
          if($node->type == 'event') {
            $event_time_value = field_get_items('node', $node, FINDIT_FIELD_EVENT_DATE);
            $event_time_render = field_view_value(
              'node',
              $node,
              FINDIT_FIELD_EVENT_DATE,
              $event_time_value[0],
              array(
                'label' => 'hidden',
                // You can't set date_plain format settings ...
                // 'type' => 'date_plain',
                'settings' => array(
                  'format_type' => 'medium',
                  'show_remaining_days' => FALSE,
                  'show_repeat_rule'    => 'show',
                ),
              ),
              $langcode
            );
            // ... However Date default puts in HTML. Bah!
            $event_time = strip_tags($event_time_render['#markup']);
            $replacements[$original] = t(
              'Event date: @time',
              array(
                '@time' => $event_time,
              ),
              array('langcode' => $langcode)
            );
          }
          else {
            $replacements[$original] = '';
          }
          break;
      }
    }
  }

  return $replacements;
}

/*
 * Helper funciton that detect if this event is still active based on event date field
 */
function findit_subscriber_is_active_event($node) {
  $event_time_value = field_get_items('node', $node, FINDIT_FIELD_EVENT_DATE);
  if(isset($event_time_value) && !empty($event_time_value)) {
    $last_event_date_item = end($event_time_value);
    if (isset($last_event_date_item['value2'])) {
      $last_event_date_value = $last_event_date_item['value2'];
    }
    else {
      $last_event_date_value = $last_event_date_item['value'];
    }
    $last_event_date = new DateObject($last_event_date_value, $last_event_date_item['timezone_db'], date_type_format($last_event_date_item['date_type']));
    if($last_event_date->getTimestamp() >= REQUEST_TIME ) {
      return TRUE;
    }
  }

  return FALSE;
}

/**
 * Implements hook_action_info() for Views Bulk Operations.
 */
function findit_subscriber_action_info() {
  return array(
    'findit_subscriber_unsubscribe' => array( // declare the function name to be used. Replace the name with your function name
      'type' => 'entity', // can be node,comment etc
      'label' => t('Unsubscribe'), // the name of the operation which is displayed to the user.
      'configurable' => FALSE,
      'vbo_configurable' => FALSE,
      'pass rows' => TRUE, // this will ensure that the entire views row is passed as part of the context in your action callback.
    ),
    'findit_subscriber_cancel_all' => array( // declare the function name to be used. Replace the name with your function name
      'type' => 'entity', // can be node,comment etc
      'label' => t('Cancel all subscriptions'), // the name of the operation which is displayed to the user.
      'configurable' => FALSE,
      'vbo_configurable' => FALSE,
      'pass rows' => TRUE, // this will ensure that the entire views row is passed as part of the context in your action callback.
      'aggregate' => TRUE,
    ),
  );
}

function findit_subscriber_unsubscribe($entity, $context = array()) {
  //Remove event from subscriber
  $row = reset($context['rows']);
  $event_delta = $row->field_data_field_subscriber_events_delta;
  array_splice($entity->{FINDIT_FIELD_SUBSCRIBER_EVENTS}[LANGUAGE_NONE], $event_delta, 1);
  entity_save('subscriber_entity', $entity);
}

function findit_subscriber_cancel_all($entity, $context = array()) {
  $entity = reset($entity);
  entity_delete('subscriber_entity', $entity->id);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function findit_subscriber_form_views_form_reminder_subscriptions_page_alter(&$form, $form_state) {
  if ($form_state['step'] == 'views_bulk_operations_confirm_form') {
    //Confirmation VBO form
    switch ($form_state['clicked_button']['#operation_id']) {
      case 'action::findit_subscriber_unsubscribe':
        $form['#vbo_confirm_form_title'] = t('Are you sure you want to unsubscribe from the following events?');
        //dpm($form);
        //dpm($form_state['selection']);
        //@todo: figure out how to get list of events, and show event titles

        break;
      case 'action::findit_subscriber_cancel_all':
        $form['#vbo_confirm_form_title'] = t('Are you sure you want to cancel all subscriptions?');
        $form['description']['#access'] = FALSE;
        break;
    }


  }
  else {
    //Hide VBO form if view result is empty (Reminder subscriptions)
    $view = $form_state['build_info']['args'][0];
    if (empty($view->result)) {
      $form['#access'] = FALSE;
    }
    else {
      $form['#attached']['js'][] = drupal_get_path('module', 'findit_subscriber') . '/js/findit_subscriber.js';
    }
  }

}


/**
 * Implements hook_form_FORM_ID_alter().
 */
function findit_subscriber_form_views_exposed_form_alter(&$form, $form_state) {
//dpm($form);
  //$form['#validate'][]='findit_subscriber_form_views_exposed_validate';
}

function findit_subscriber_form_views_exposed_validate(&$form, &$form_state) {
  //Replace mobile number with vnid, since voipnumberfield doesn't expose phone number to the Views
  $mobile_number = $form_state['values']['field_subscriber_voipnumber_vnid'];
  if($mobile_number) {
    $voipnumbers = VoIPNumber::getVoipNumbersByNumber($mobile_number, 'subscriber_entity');
    $voipnumber = reset($voipnumbers);
    if ($voipnumber) {
      $vnid = $voipnumber->getVnid();
      $form_state['values']['field_subscriber_voipnumber_vnid'] = $vnid;
    }
  }
}

/**
 * Implementation of hook_views_api().
 */
function findit_subscriber_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'findit_subscriber') . '/views',
  );
}


///////TEST

/*
 * $node=node_load(36);
drupal_mail(
            'findit_subscriber',
            'event_post_notification',
            'tt@tt.tt',
            language_default(),
            array(
              'node' => $node,
              'action' => 'update',
            )
          );


$node = node_load(51);
$original = variable_get('findit_subscriber_post_notify_mail_subject', '');
      $text = token_replace($original, array('node' => $node));

*/