<?php

/**
 * @file
 * Install settings for Find It RESTWS module.
 */

/**
 * Implements hook_install().
 */
function findit_restws_install() {
  // Set permission so that Anonymous and Auth users can view REST API.
  $permissions = array(
    'access resource node',
  );

  user_role_grant_permissions(DRUPAL_ANONYMOUS_RID, $permissions);
  user_role_grant_permissions(DRUPAL_AUTHENTICATED_RID, $permissions);
}