<?php

/**
 * @file
 * Automatically assigns the service provider role for new users.
 */

/**
 * Implements hook_form_FORM_ID_alter().
 */
function findit_auto_service_provider_form_user_register_form_alter(&$form, $form_state) {
  array_unshift($form['#submit'], 'findit_auto_service_provider_form_user_register_submit');
}

/**
 * Submit handler for the user registration form.
 */
function findit_auto_service_provider_form_user_register_submit(&$form, &$form_state) {
  $rid = user_role_load_by_name(FINDIT_ROLE_SERVICE_PROVIDER)->rid;
  $roles = user_roles(TRUE);
  $form_state['values']['roles'][$rid] = $roles[$rid];
}
